//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public string login { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> role_id { get; set; }
        public string session_id { get; set; }
        public string name { get; set; }
        public string last_name { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string street_nr { get; set; }
        public string apartment_nr { get; set; }
        public string phone_number { get; set; }
    
        public virtual roles roles { get; set; }
    }
}
